INIT_PROMPT = """You are a helpful assistant. You are here to help user to write a SEO friendly article."""
RESPOND_PROMPT = """Following the previous messages, you should fill article information into a 
json object. The format is as follows: 
{
  "title": "fill the title of the article",
  "introduction": "briefly introduction about the content, the goal of article",
  "tags": [
    {
      "type": "fill with h1, h2 or h3",
      "value": "fill with heading text",
    },
    {
      "type": "image",
      "prompt": "fill with a prompt which should be used to generate image by AI",
    },
    {
      "type": "paragraph",
      "prompt": "short description of the paragraph",
      "value": "text value generated by the above prompt"
    }
  ]
} 
Please fill the json object with your article content. The length of article should be between 1000 - 2000 words. 
Each heading should be followed by a prompt to generate image and at least one paragraph. 
Please return me only the json object with the content filled."""
